create table if not exists public.shop_state (
  id integer primary key check (id = 1),
  coins integer not null default 0 check (coins >= 0),
  last_login timestamptz
);

insert into public.shop_state (id, coins, last_login)
values (1, 0, null)
on conflict (id) do nothing;

create table if not exists public.shop_purchases (
  id bigint generated by default as identity primary key,
  product text not null,
  price integer not null check (price > 0),
  created_at timestamptz not null default now()
);
